=== andrea-chizzola/ingswAM2021-Corigliano-Colombo-Chizzola/AM19/AM19/src/main/resources/XML/leaderCards.dtd
<?xml version="1.0" encoding="UTF-8" ?>

        <!ELEMENT leaderCards (leader)*>
        <!ELEMENT leader (requirements, effect)>

        <!-- leader card requirements -->
        <!ELEMENT requirements ((cardRequirement)|(resourceRequirement))>
        <!-- requirement of type 1 -->
        <!ELEMENT cardRequirement (card)+>
        <!ELEMENT card EMPTY>
        <!-- requirement of type 2 -->
        <!ELEMENT resourceRequirement (resquantity)+>
        <!ELEMENT resquantity EMPTY>

        <!-- leader card effects -->
        <!ELEMENT effect (discount|whiteMarble|production|extraSlot)>
        <!-- effect of type 1 -->
        <!ELEMENT discount EMPTY>
        <!-- effect of type 2 -->
        <!ELEMENT whiteMarble EMPTY>
        <!-- effect of type 3 -->
        <!ELEMENT production (materials, products)>
        <!ELEMENT materials (resquantity)+>
        <!ELEMENT products (resquantity)+>
        <!-- effect of type 4 -->
        <!ELEMENT extraSlot (resquantity)>

        <!-- attributes of the elements -->
        <!ATTLIST leader points CDATA #REQUIRED>
        <!ATTLIST card color (GREEN|BLUE|YELLOW|PURPLE) #REQUIRED>
        <!ATTLIST card level CDATA #REQUIRED>
        <!ATTLIST card amount CDATA #REQUIRED>
        <!ATTLIST resquantity resource (COINS|SERVANTS|STONES|FAITH|SHIELDS) #REQUIRED>
        <!ATTLIST resquantity amount CDATA #REQUIRED>
        <!ATTLIST whiteMarble resource (COINS|SERVANTS|STONES|FAITH|SHIELDS) #REQUIRED>
        <!ATTLIST discount resource (COINS|SERVANTS|STONES|FAITH|SHIELDS) #REQUIRED>

=== andrea-chizzola/ingswAM2021-Corigliano-Colombo-Chizzola/AM19/AM19/src/main/resources/XML/defaultLeaderCards.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!-- test: first leader card -->
<!--<!DOCTYPE leaderCards SYSTEM
        "C:\Users\Davide\Desktop\ingswAM2021-Corigliano-Colombo-Chizzola\AM19\AM19\src\main\resources\XML\leaderCards.dtd">
        -->
<leaderCards>
    <leader points = "2">
        <requirements>
            <cardRequirement>
                <card color="YELLOW" level="1" amount="1"/>
                <card color="GREEN" level="1" amount="1"/>
            </cardRequirement>
        </requirements>
        <effect>
            <discount>
                <resquantity amount="1" resource="SERVANTS"/>
            </discount>
        </effect>
    </leader>

</leaderCards>

=== andrea-chizzola/ingswAM2021-Corigliano-Colombo-Chizzola/AM19/AM19/src/test/java/it/polimi/ingsw/LeaderCardsTest.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!-- test: first leader card -->
<!DOCTYPE leaderCards SYSTEM
        "C:\Users\Davide\Desktop\ingswAM2021-Corigliano-Colombo-Chizzola\AM19\AM19\src\main\resources\XML\leaderCards.dtd">
<leaderCards>
    <leader points = "2">
        <requirements>
            <cardRequirement>
                <card color="YELLOW" level="1" amount="1"/>
                <card color="GREEN" level="1" amount="1"/>
            </cardRequirement>
        </requirements>
        <effect>
            <discount resource = "SERVANTS"/>
        </effect>
    </leader>
    <!-- -->
    <leader points = "3">
        <requirements>
            <resourceRequirement>
                <resquantity amount="5" resource="COINS"/>
            </resourceRequirement>
        </requirements>
        <effect>
            <extraSlot>
                <resquantity amount="2" resource="STONES"/>
            </extraSlot>
        </effect>
    </leader>
    <!-- -->
    <leader points = "5">
        <requirements>
            <cardRequirement>
                <card amount="2" color="YELLOW" level="1"/>
                <card amount="1" color="BLUE" level="1"/>
            </cardRequirement>
        </requirements>
        <effect>
            <whiteMarble resource="SERVANTS"/>
        </effect>
    </leader>
    <!-- -->
    <leader points = "4">
        <requirements>
            <cardRequirement>
                <card amount="1" color="YELLOW" level="2"/>
            </cardRequirement>
        </requirements>
        <effect>
            <production>
                <materials>
                    <resquantity amount="1" resource="SHIELDS"/>
                </materials>
                <products>
                    <resquantity amount="1" resource="FAITH"/>
                </products>
            </production>
        </effect>
    </leader>
</leaderCards>
